[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "composer", "nodejs_20"]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "composer install --ignore-platform-req=ext-gd --no-dev --optimize-autoloader"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"