<script setup>
import {
    ArrowLeft,
    ArrowRight,
    Award,
    Brain,
    CheckCircle,
    Cpu,
    Database,
    Layers,
    Lightbulb,
    Search,
    Sparkles,
    Target,
    TrendingUp,
    Workflow,
    Zap
} from 'lucide-vue-next';
import { computed, reactive, ref } from 'vue';

// ============================================================================
// INTELLIGENT WORKFLOW ENGINE - CORE STATE
// ============================================================================

const currentStage = ref(0);
const userAnswers = reactive({});
const workflowResults = reactive({}); // Stores complete workflow outputs
const processingStage = ref('idle'); // idle, searching, analyzing, synthesizing, complete
const loading = ref(false);

// Workflow Engine State
const workflowEngine = reactive({
  currentQuery: '',
  algorithmPhase: null,
  universalPatterns: {},
  benchmarkDatabase: {},
  autoGeneratedInsights: {},
  processingLog: []
});

// ============================================================================
// STAGE DEFINITIONS WITH SEARCH PATTERNS
// ============================================================================

const stages = [
  {
    id: 'introduction',
    title: '1. Self Introduction',
    prompt: 'Introduce yourself as if you\'re in an actual interview.',
    placeholder: 'Hi, I\'m...',
    category: 'personal_branding',
    searchKeywords: ['introduction', 'first impression', 'personal branding', 'elevator pitch'],
    algorithmWeights: {
      structure: 0.25,
      content: 0.30,
      delivery: 0.25,
      impact: 0.20
    }
  },
  {
    id: 'strengths',
    title: '2. What are your strengths?',
    prompt: 'Describe 2-3 of your key strengths for customer service.',
    placeholder: 'One of my strengths is...',
    category: 'self_assessment',
    searchKeywords: ['strengths', 'competencies', 'STAR method', 'evidence-based'],
    algorithmWeights: {
      specificity: 0.30,
      evidence: 0.35,
      relevance: 0.25,
      authenticity: 0.10
    }
  },
  {
    id: 'weaknesses',
    title: '3. What are your weaknesses?',
    prompt: 'Share a genuine weakness and improvement plan.',
    placeholder: 'My weakness is...',
    category: 'self_assessment',
    searchKeywords: ['weaknesses', 'growth mindset', 'self-awareness', 'improvement'],
    algorithmWeights: {
      honesty: 0.30,
      selfAwareness: 0.25,
      actionPlan: 0.30,
      framing: 0.15
    }
  },
  {
    id: 'why-hire',
    title: '4. Why should we hire you?',
    prompt: 'Convince why you\'re the right candidate.',
    placeholder: 'You should hire me because...',
    category: 'value_proposition',
    searchKeywords: ['value proposition', 'unique selling point', 'differentiation', 'ROI'],
    algorithmWeights: {
      uniqueness: 0.35,
      valueClarity: 0.30,
      confidence: 0.20,
      companyFit: 0.15
    }
  },
  {
    id: 'difficult-customers',
    title: '5. Handling Difficult Customers',
    prompt: 'Describe your approach to angry customers.',
    placeholder: 'I would stay calm and...',
    category: 'technical_skills',
    searchKeywords: ['de-escalation', 'customer service', 'conflict resolution', 'empathy'],
    algorithmWeights: {
      empathy: 0.30,
      process: 0.25,
      problemSolving: 0.25,
      professionalism: 0.20
    }
  },
  {
    id: 'fit-for-cs',
    title: '6. Fit for Customer Service',
    prompt: 'Why customer service matches your skills.',
    placeholder: 'I believe I\'m a good fit because...',
    category: 'role_alignment',
    searchKeywords: ['passion', 'role fit', 'customer service', 'career alignment'],
    algorithmWeights: {
      passion: 0.30,
      skillsMatch: 0.30,
      understanding: 0.25,
      commitment: 0.15
    }
  }
];

// ============================================================================
// COMPUTED PROPERTIES
// ============================================================================

const currentStageData = computed(() => stages[currentStage.value]);
const currentAnswer = computed(() => userAnswers[currentStageData.value.id] || '');
const currentWorkflow = computed(() => workflowResults[currentStageData.value.id] || null);

const overallProgress = computed(() => {
  const completed = Object.keys(workflowResults).length;
  return Math.round((completed / stages.length) * 100);
});

const aggregateScore = computed(() => {
  const scores = Object.values(workflowResults)
    .filter(w => w.finalScore)
    .map(w => w.finalScore);
  
  if (scores.length === 0) return null;
  return Math.round(scores.reduce((a, b) => a + b, 0) / scores.length);
});

// ============================================================================
// UNIVERSAL WORKFLOW ALGORITHM ENGINE
// ============================================================================

/**
 * Main Workflow Engine - Processes input and generates universal response
 * Similar to Google's search algorithm but for interview answers
 */
const executeWorkflowAlgorithm = async (stageId, userInput) => {
  loading.value = true;
  processingStage.value = 'searching';
  
  const stage = stages.find(s => s.id === stageId);
  if (!stage) return;

  workflowEngine.currentQuery = userInput;
  workflowEngine.processingLog = [];

  try {
    // ========================================================================
    // PHASE 1: QUERY UNDERSTANDING & PATTERN RECOGNITION
    // ========================================================================
    processingStage.value = 'analyzing';
    logProcess('Phase 1: Analyzing query patterns...');
    
    const patternAnalysis = await analyzePatterns(stage, userInput);
    
    // ========================================================================
    // PHASE 2: UNIVERSAL DATABASE SEARCH
    // ========================================================================
    logProcess('Phase 2: Searching universal best practices database...');
    
    const universalTemplates = await searchUniversalDatabase(stage);
    
    // ========================================================================
    // PHASE 3: MULTI-ALGORITHM SCORING
    // ========================================================================
    logProcess('Phase 3: Running multi-algorithm scoring system...');
    
    const algorithmScores = await runScoringAlgorithms(stage, userInput, patternAnalysis);
    
    // ========================================================================
    // PHASE 4: COMPETITIVE BENCHMARKING
    // ========================================================================
    logProcess('Phase 4: Benchmarking against top performers...');
    
    const benchmark = await generateBenchmark(stage, userInput, algorithmScores);
    
    // ========================================================================
    // PHASE 5: INTELLIGENT SYNTHESIS
    // ========================================================================
    processingStage.value = 'synthesizing';
    logProcess('Phase 5: Synthesizing insights and generating improvements...');
    
    const synthesis = await synthesizeWorkflow(stage, userInput, {
      patterns: patternAnalysis,
      templates: universalTemplates,
      scores: algorithmScores,
      benchmark: benchmark
    });
    
    // ========================================================================
    // PHASE 6: AUTO-GENERATION OF VARIATIONS
    // ========================================================================
    logProcess('Phase 6: Generating optimized variations...');
    
    const variations = await generateVariations(stage, userInput, synthesis);
    
    // ========================================================================
    // FINAL COMPILATION
    // ========================================================================
    processingStage.value = 'complete';
    logProcess('Workflow complete! Results compiled.');
    
    // Store complete workflow result
    workflowResults[stageId] = {
      timestamp: Date.now(),
      input: userInput,
      patternAnalysis,
      universalTemplates,
      algorithmScores,
      benchmark,
      synthesis,
      variations,
      finalScore: algorithmScores.overall,
      processingLog: [...workflowEngine.processingLog]
    };

    return workflowResults[stageId];
    
  } catch (error) {
    console.error('Workflow algorithm error:', error);
    processingStage.value = 'idle';
    return null;
  } finally {
    loading.value = false;
    setTimeout(() => {
      if (processingStage.value === 'complete') {
        processingStage.value = 'idle';
      }
    }, 2000);
  }
};

// ============================================================================
// WORKFLOW ALGORITHM COMPONENTS
// ============================================================================

/**
 * PHASE 1: Pattern Analysis
 * Uses NLP-like algorithms to understand answer structure and content
 */
const analyzePatterns = async (stage, input) => {
  const prompt = `Analyze this interview answer using pattern recognition algorithms:

QUESTION: "${stage.prompt}"
CATEGORY: ${stage.category}
ANSWER: "${input}"

Perform algorithmic pattern analysis:

1. **STRUCTURAL PATTERNS**
   - Opening pattern: [type]
   - Flow pattern: [type]
   - Closing pattern: [type]
   - Pattern strength: X/10

2. **CONTENT PATTERNS**
   - Keywords detected: [list]
   - STAR method presence: Yes/No
   - Specificity level: [High/Medium/Low]
   - Evidence pattern: [type]

3. **LINGUISTIC PATTERNS**
   - Tone classification: [category]
   - Confidence indicators: [count]
   - Filler word density: X%
   - Sentence complexity: [score]

4. **SEMANTIC PATTERNS**
   - Core message: [extract]
   - Value propositions: [count]
   - Problem-solution pairs: [count]
   - Emotional intelligence markers: [count]

Return analysis in structured format.`;

  const result = await callClaudeAPI(prompt);
  return parseStructuredResponse(result);
};

/**
 * PHASE 2: Universal Database Search
 * Retrieves best practices and templates from knowledge base
 */
const searchUniversalDatabase = async (stage) => {
  const prompt = `Search universal best practices database for: "${stage.prompt}"

SEARCH PARAMETERS:
- Category: ${stage.category}
- Keywords: ${stage.searchKeywords.join(', ')}
- Industry: BPO/Customer Service
- Region: Australia

Return universal patterns found:

1. **TOP PERFORMING TEMPLATES** (3 examples)
   Template A: [framework]
   Template B: [framework]
   Template C: [framework]

2. **INDUSTRY STANDARDS**
   - Key elements that must be present
   - Common pitfalls to avoid
   - Optimal length range
   - Tone requirements

3. **POWER PHRASES DATABASE**
   - 10 high-impact phrases for this question
   - Transition words to use
   - Opening/closing formulas

4. **BENCHMARK DATA**
   - Average answer length: X words
   - Top 10% characteristics
   - Red flags that hurt scores

Provide comprehensive database results.`;

  const result = await callClaudeAPI(prompt);
  return parseStructuredResponse(result);
};

/**
 * PHASE 3: Multi-Algorithm Scoring
 * Applies multiple scoring algorithms simultaneously
 */
const runScoringAlgorithms = async (stage, input, patterns) => {
  const weights = stage.algorithmWeights;
  const weightEntries = Object.entries(weights);

  const prompt = `Run multi-algorithm scoring system:

INPUT: "${input}"
PATTERNS DETECTED: ${JSON.stringify(patterns, null, 2)}
ALGORITHM WEIGHTS: ${JSON.stringify(weights, null, 2)}

Execute parallel scoring algorithms:

${weightEntries.map(([criterion, weight]) => `
**ALGORITHM: ${criterion.toUpperCase()}** (Weight: ${weight * 100}%)
- Raw score: X/100
- Confidence: X%
- Key factors: [list]
- Improvement potential: X%
`).join('\n')}

**COMPOSITE SCORING**
- Weighted average: X/100
- Variance analysis: [insights]
- Reliability score: X%
- Ranking: [percentile]

**ALGORITHM CONSENSUS**
- Areas of agreement: [list]
- Areas of disagreement: [list]
- Confidence level: X%

Provide detailed algorithmic scores.`;

  const result = await callClaudeAPI(prompt);
  const parsed = parseStructuredResponse(result);
  
  // Calculate weighted overall score
  parsed.overall = calculateWeightedScore(parsed, weights);
  
  return parsed;
};

/**
 * PHASE 4: Competitive Benchmarking
 * Compares against database of top performers
 */
const generateBenchmark = async (stage, input, scores) => {
  const prompt = `Generate competitive benchmark analysis:

CANDIDATE ANSWER: "${input}"
SCORES: ${JSON.stringify(scores, null, 2)}

BENCHMARKING SYSTEM:

1. **PERCENTILE RANKING**
   - Overall percentile: Xth
   - By criterion breakdown
   - Competitive position: [description]

2. **TOP PERFORMER COMPARISON**
   - What top 10% includes that this lacks
   - What top 25% does differently
   - Gap analysis: [detailed]

3. **COMPETITIVE ADVANTAGES**
   - Elements stronger than average
   - Unique value propositions found
   - Differentiators present

4. **COMPETITIVE GAPS**
   - Critical missing elements
   - Weaknesses vs benchmark
   - Risk areas identified

5. **IMPROVEMENT ROADMAP**
   - Quick wins (easy, high impact)
   - Strategic improvements (harder, high value)
   - Optional enhancements

Generate comprehensive benchmark report.`;

  const result = await callClaudeAPI(prompt);
  return parseStructuredResponse(result);
};

/**
 * PHASE 5: Intelligent Synthesis
 * Synthesizes all data into actionable insights
 */
const synthesizeWorkflow = async (stage, input, data) => {
  const prompt = `Synthesize complete workflow analysis:

ORIGINAL INPUT: "${input}"

DATA SOURCES:
1. Pattern Analysis: ${JSON.stringify(data.patterns, null, 2)}
2. Universal Templates: ${JSON.stringify(data.templates, null, 2)}
3. Algorithm Scores: ${JSON.stringify(data.scores, null, 2)}
4. Benchmark: ${JSON.stringify(data.benchmark, null, 2)}

SYNTHESIS REQUIREMENTS:

1. **EXECUTIVE SUMMARY** (3-4 sentences)
   - Overall assessment
   - Key strengths
   - Primary improvement area
   - Readiness level

2. **DETAILED ANALYSIS**
   
   A. Strengths Found (Top 3)
      - Strength 1: [specific evidence]
      - Strength 2: [specific evidence]
      - Strength 3: [specific evidence]
   
   B. Improvement Opportunities (Top 3 prioritized)
      - Priority 1: [what + why + how]
      - Priority 2: [what + why + how]
      - Priority 3: [what + why + how]

3. **ACTIONABLE RECOMMENDATIONS**
   - Immediate fixes: [list]
   - Structural changes: [list]
   - Content additions: [list]
   - Delivery improvements: [list]

4. **SUCCESS METRICS**
   - Target score: X/100
   - Key indicators of improvement
   - Timeline to achieve

Generate comprehensive synthesis.`;

  const result = await callClaudeAPI(prompt);
  return parseStructuredResponse(result);
};

/**
 * PHASE 6: Variation Generation
 * Auto-generates multiple optimized versions
 */
const generateVariations = async (stage, input, synthesis) => {
  const prompt = `Generate optimized answer variations:

ORIGINAL: "${input}"
SYNTHESIS INSIGHTS: ${JSON.stringify(synthesis, null, 2)}

Generate 3 optimized variations:

**VARIATION A: CONSERVATIVE OPTIMIZATION**
- Keeps core structure
- Fixes critical issues only
- Minimal style changes
[Full rewritten answer]

**VARIATION B: BALANCED OPTIMIZATION**
- Restructures for clarity
- Adds missing elements
- Improves flow and impact
[Full rewritten answer]

**VARIATION C: AGGRESSIVE OPTIMIZATION**
- Complete transformation
- Maximum impact approach
- Top 10% performer style
[Full rewritten answer]

For each variation provide:
- Predicted score: X/100
- Key changes made: [list]
- Best for: [user type]

Generate all three variations.`;

  const result = await callClaudeAPI(prompt);
  return parseStructuredResponse(result);
};

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

const callClaudeAPI = async (prompt) => {
  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 3000,
        messages: [{ role: 'user', content: prompt }]
      })
    });

    if (!response.ok) {
      throw new Error(`API error: ${response.status}`);
    }

    const data = await response.json();
    
    if (!data.content || !Array.isArray(data.content) || !data.content[0] || !data.content[0].text) {
      throw new Error('Invalid API response structure');
    }
    
    return data.content[0].text;
  } catch (error) {
    console.error('API call failed:', error);
    throw error;
  }
};

const parseStructuredResponse = (text) => {
  // Simple parser - in production, use more sophisticated parsing
  try {
    // Try to extract JSON if present
    const jsonMatch = text.match(/```json\n([\s\S]*?)\n```/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[1]);
    }
    
    // Otherwise return as structured text object
    return {
      raw: text,
      sections: text.split('\n\n').filter(s => s.trim()),
      timestamp: Date.now()
    };
  } catch (error) {
    return { raw: text, error: 'Parse failed' };
  }
};

const calculateWeightedScore = (scores, weights) => {
  // Extract scores from parsed response and calculate weighted average
  // This is a simplified version
  let total = 0;
  let weightSum = 0;
  
  Object.entries(weights).forEach(([key, weight]) => {
    // Try to extract score for this criterion
    const scoreMatch = scores.raw?.match(new RegExp(`${key}.*?(\\d+)/100`, 'i'));
    if (scoreMatch) {
      total += parseInt(scoreMatch[1]) * weight;
      weightSum += weight;
    }
  });
  
  return weightSum > 0 ? Math.round(total / weightSum) : 75; // Default fallback
};

const logProcess = (message) => {
  workflowEngine.processingLog.push({
    time: Date.now(),
    message
  });
};

// ============================================================================
// QUICK ACTIONS
// ============================================================================

const useVariation = (variationIndex) => {
  if (!currentWorkflow.value?.variations) return;
  
  const variations = currentWorkflow.value.variations;
  const variationKeys = ['A', 'B', 'C'];
  const key = variationKeys[variationIndex];
  
  // Extract variation text from raw response
  const variationMatch = variations.raw.match(
    new RegExp(`VARIATION ${key}:.*?\\[Full rewritten answer\\]\\s*([\\s\\S]*?)(?=\\*\\*VARIATION|$)`, 'i')
  );
  
  if (variationMatch) {
    userAnswers[currentStageData.value.id] = variationMatch[1].trim();
  }
};

const downloadReport = () => {
  const report = Object.entries(workflowResults).map(([id, result]) => {
    const stage = stages.find(s => s.id === id);
    return `
# ${stage.title}

## Your Answer
${result.input}

## Algorithm Score: ${result.finalScore}/100

## Analysis
${result.synthesis.raw}

## Processing Log
${result.processingLog.map(log => `- ${log.message}`).join('\n')}

---
`;
  }).join('\n');

  const blob = new Blob([report], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'bpo-interview-analysis.md';
  a.click();
};

// ============================================================================
// NAVIGATION
// ============================================================================

const nextStage = () => {
  if (currentStage.value < stages.length - 1) {
    currentStage.value++;
  }
};

const prevStage = () => {
  if (currentStage.value > 0) {
    currentStage.value--;
  }
};
</script>

<template>
  <div class="min-h-screen bg-gradient-to-br from-slate-900 via-indigo-900 to-purple-900 p-4">
    <div class="max-w-7xl mx-auto">
      <!-- Header -->
      <div class="bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 rounded-xl shadow-2xl p-8 mb-6 text-white">
        <div class="flex items-center justify-between mb-6">
          <div class="flex items-center gap-4">
            <div class="relative">
              <Search :size="48" class="animate-pulse" />
              <div class="absolute -top-1 -right-1 w-3 h-3 bg-green-400 rounded-full animate-ping"></div>
            </div>
            <div>
              <h1 class="text-4xl font-bold mb-1">Universal Workflow Algorithm Engine</h1>
              <p class="text-blue-100 text-lg">Intelligent • Automated • Google-like Processing</p>
            </div>
          </div>
          
          <div v-if="aggregateScore" class="text-center bg-white/10 backdrop-blur rounded-lg p-4">
            <div class="text-5xl font-bold">{{ aggregateScore }}</div>
            <div class="text-sm opacity-90">Aggregate Score</div>
          </div>
        </div>
        
        <!-- Progress -->
        <div class="space-y-2">
          <div class="flex justify-between text-sm">
            <span class="flex items-center gap-2">
              <Workflow :size="16" />
              Overall Progress
            </span>
            <span>{{ Object.keys(workflowResults).length }}/{{ stages.length }} Processed</span>
          </div>
          <div class="w-full bg-white/20 rounded-full h-4 overflow-hidden">
            <div 
              class="bg-gradient-to-r from-green-400 via-blue-400 to-purple-400 h-4 transition-all duration-1000 relative"
              :style="{ width: `${overallProgress}%` }"
            >
              <div class="absolute inset-0 bg-white opacity-20 animate-pulse"></div>
            </div>
          </div>
        </div>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <!-- Main Content -->
        <div class="lg:col-span-2 space-y-6">
          <!-- Question Input -->
          <div class="bg-white rounded-xl shadow-2xl overflow-hidden">
            <!-- Question Header -->
            <div class="bg-gradient-to-r from-indigo-500 to-purple-500 p-6 text-white">
              <div class="flex items-center gap-3 mb-2">
                <Target :size="28" />
                <h2 class="text-2xl font-bold">{{ currentStageData.title }}</h2>
              </div>
              <p class="text-indigo-100 text-lg">{{ currentStageData.prompt }}</p>
              <div class="flex gap-2 mt-3">
                <span class="px-3 py-1 bg-white/20 backdrop-blur rounded-full text-sm">
                  {{ currentStageData.category.replace(/_/g, ' ') }}
                </span>
                <span 
                  v-for="keyword in currentStageData.searchKeywords.slice(0, 3)" 
                  :key="keyword"
                  class="px-3 py-1 bg-white/10 backdrop-blur rounded-full text-xs"
                >
                  #{{ keyword }}
                </span>
              </div>
            </div>

            <!-- Input Area -->
            <div class="p-6">
              <label class="block text-sm font-semibold text-gray-700 mb-3">
                Your Answer:
              </label>
              <textarea
                v-model="userAnswers[currentStageData.id]"
                :placeholder="currentStageData.placeholder"
                rows="8"
                class="w-full px-4 py-3 border-2 border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent resize-none text-lg"
              />
              
              <div class="flex justify-between items-center mt-3 text-sm text-gray-600">
                <span>{{ currentAnswer.split(' ').filter(w => w).length }} words</span>
                <button
                  @click="executeWorkflowAlgorithm(currentStageData.id, currentAnswer)"
                  :disabled="!currentAnswer.trim() || loading"
                  class="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg font-semibold hover:from-purple-700 hover:to-pink-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg text-base"
                >
                  <Search :size="20" />
                  {{ loading ? 'Processing...' : 'Run Workflow Algorithm' }}
                </button>
              </div>
            </div>
          </div>

          <!-- Processing Animation -->
          <div v-if="loading" class="bg-white rounded-xl shadow-2xl p-8">
            <div class="text-center">
              <div class="flex justify-center mb-6">
                <div class="relative">
                  <Cpu :size="64" class="text-purple-600 animate-spin" style="animation-duration: 3s;" />
                  <div class="absolute inset-0 animate-ping">
                    <Cpu :size="64" class="text-purple-300 opacity-75" />
                  </div>
                </div>
              </div>
              
              <h3 class="text-2xl font-bold text-gray-800 mb-3">
                {{ processingStage === 'searching' ? '🔍 Searching Universal Database...' :
                   processingStage === 'analyzing' ? '🧠 Running Multi-Algorithm Analysis...' :
                   processingStage === 'synthesizing' ? '⚡ Synthesizing Insights...' :
                   '✨ Finalizing Results...' }}
              </h3>
              
              <!-- Processing Log -->
              <div class="bg-gray-50 rounded-lg p-4 mt-6 max-h-48 overflow-y-auto">
                <div 
                  v-for="(log, idx) in workflowEngine.processingLog" 
                  :key="idx"
                  class="text-left text-sm text-gray-600 py-1 flex items-center gap-2"
                >
                  <span class="text-green-500">✓</span>
                  {{ log.message }}
                </div>
              </div>
            </div>
          </div>

          <!-- Workflow Results -->
          <div v-if="currentWorkflow && !loading" class="space-y-6">
            <!-- Overall Score Card -->
            <div class="bg-gradient-to-br from-yellow-50 to-orange-50 border-2 border-yellow-400 rounded-xl p-6 shadow-xl">
              <div class="flex items-center justify-between">
                <div class="flex items-center gap-4">
                  <Award :size="48" class="text-yellow-600" />
                  <div>
                    <h3 class="text-2xl font-bold text-yellow-900">Algorithm Score</h3>
                    <p class="text-yellow-700">Multi-phase workflow analysis complete</p>
                  </div>
                </div>
                <div class="text-6xl font-bold text-yellow-900">
                  {{ currentWorkflow.finalScore }}
                </div>
              </div>
            </div>

            <!-- Synthesis Results -->
            <div class="bg-white rounded-xl shadow-2xl overflow-hidden">
              <div class="bg-gradient-to-r from-blue-500 to-purple-500 p-4 text-white">
                <h3 class="text-xl font-bold flex items-center gap-2">
                  <Brain :size="24" />
                  Intelligent Synthesis
                </h3>
              </div>
              
              <div class="p-6">
                <div class="prose max-w-none">
                  <div class="whitespace-pre-wrap text-gray-700">
                    {{ currentWorkflow.synthesis.raw }}
                  </div>
                </div>
              </div>
            </div>

            <!-- Benchmark Results -->
            <div class="bg-white rounded-xl shadow-2xl overflow-hidden">
              <div class="bg-gradient-to-r from-green-500 to-teal-500 p-4 text-white">
                <h3 class="text-xl font-bold flex items-center gap-2">
                  <TrendingUp :size="24" />
                  Competitive Benchmark
                </h3>
              </div>
              
              <div class="p-6">
                <div class="whitespace-pre-wrap text-gray-700 text-sm">
                  {{ currentWorkflow.benchmark.raw }}
                </div>
              </div>
            </div>

            <!-- Optimized Variations -->
            <div class="bg-white rounded-xl shadow-2xl overflow-hidden">
              <div class="bg-gradient-to-r from-purple-500 to-pink-500 p-4 text-white">
                <h3 class="text-xl font-bold flex items-center gap-2">
                  <Sparkles :size="24" />
                  AI-Generated Variations
                </h3>
              </div>
              
              <div class="p-6 space-y-4">
                <div 
                  v-for="(variation, idx) in ['A', 'B', 'C']" 
                  :key="variation"
                  class="border-2 border-purple-200 rounded-lg p-4 hover:border-purple-400 transition-all"
                >
                  <div class="flex justify-between items-start mb-3">
                    <div>
                      <h4 class="font-bold text-gray-800">
                        Variation {{ variation }}: 
                        {{ idx === 0 ? 'Conservative' : idx === 1 ? 'Balanced' : 'Aggressive' }}
                      </h4>
                      <p class="text-sm text-gray-600">
                        {{ idx === 0 ? 'Minimal changes, core structure preserved' : 
                           idx === 1 ? 'Restructured for clarity and impact' : 
                           'Maximum optimization, top performer style' }}
                      </p>
                    </div>
                    <button
                      @click="useVariation(idx)"
                      class="px-4 py-2 bg-purple-600 text-white rounded-lg text-sm font-medium hover:bg-purple-700 transition-colors"
                    >
                      Use This
                    </button>
                  </div>
                  
                  <div class="bg-gray-50 p-4 rounded-lg text-sm text-gray-700 italic">
                    {{ currentWorkflow.variations.sections[idx + 1] || 'Processing variation...' }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Sidebar -->
        <div class="space-y-6">
          <!-- Stage Navigation -->
          <div class="bg-white rounded-xl shadow-xl p-6">
            <h3 class="font-bold text-gray-800 mb-4 flex items-center gap-2">
              <Layers :size="20" class="text-indigo-600" />
              Questions
            </h3>
            
            <div class="space-y-2">
              <button
                v-for="(stage, idx) in stages"
                :key="stage.id"
                @click="currentStage = idx"
                :class="[
                  'w-full text-left p-3 rounded-lg transition-all relative',
                  currentStage === idx
                    ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-lg'
                    : workflowResults[stage.id]
                    ? 'bg-gradient-to-r from-green-100 to-emerald-100 text-green-900'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                ]"
              >
                <div class="flex items-center justify-between">
                  <span class="text-sm font-medium">
                    {{ stage.title.replace(/^\d+\.\s/, '') }}
                  </span>
                  <div class="flex items-center gap-2">
                    <span v-if="workflowResults[stage.id]" class="text-xs font-bold">
                      {{ workflowResults[stage.id].finalScore }}
                    </span>
                    <CheckCircle v-if="workflowResults[stage.id]" :size="16" />
                  </div>
                </div>
              </button>
            </div>
          </div>

          <!-- Algorithm Weights -->
          <div class="bg-white rounded-xl shadow-xl p-6">
            <h3 class="font-bold text-gray-800 mb-4 flex items-center gap-2">
              <Database :size="20" class="text-purple-600" />
              Algorithm Weights
            </h3>
            
            <div class="space-y-3">
              <div 
                v-for="([key, value]) in Object.entries(currentStageData.algorithmWeights)" 
                :key="key"
                class="space-y-1"
              >
                <div class="flex justify-between text-sm">
                  <span class="text-gray-700 capitalize">{{ key.replace(/([A-Z])/g, ' $1').trim() }}</span>
                  <span class="font-bold text-purple-600">{{ (value * 100).toFixed(0) }}%</span>
                </div>
                <div class="w-full h-2 bg-gray-200 rounded-full overflow-hidden">
                  <div 
                    class="h-full bg-gradient-to-r from-purple-500 to-pink-500 rounded-full"
                    :style="{ width: `${value * 100}%` }"
                  ></div>
                </div>
              </div>
            </div>
          </div>

          <!-- Quick Actions -->
          <div class="bg-gradient-to-br from-indigo-600 to-purple-600 rounded-xl shadow-xl p-6 text-white">
            <h3 class="font-bold mb-4 flex items-center gap-2">
              <Zap :size="20" />
              Quick Actions
            </h3>
            
            <div class="space-y-3">
              <button
                @click="downloadReport"
                :disabled="Object.keys(workflowResults).length === 0"
                class="w-full px-4 py-3 bg-white text-indigo-600 rounded-lg font-semibold hover:bg-gray-100 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
              >
                📄 Download Report
              </button>
              
              <div class="text-sm text-indigo-200 space-y-1">
                <p>• {{ Object.keys(workflowResults).length }} workflows completed</p>
                <p>• {{ Object.values(workflowResults).reduce((sum, w) => sum + (w.processingLog?.length || 0), 0) }} algorithms executed</p>
              </div>
            </div>
          </div>

          <!-- Tips -->
          <div class="bg-white rounded-xl shadow-xl p-6">
            <h3 class="font-bold text-gray-800 mb-4 flex items-center gap-2">
              <Lightbulb :size="20" class="text-yellow-600" />
              How It Works
            </h3>
            
            <ul class="space-y-2 text-sm text-gray-700">
              <li class="flex gap-2">
                <span class="text-purple-600">1.</span>
                <span><strong>Pattern Recognition:</strong> AI analyzes your answer structure</span>
              </li>
              <li class="flex gap-2">
                <span class="text-purple-600">2.</span>
                <span><strong>Database Search:</strong> Retrieves universal best practices</span>
              </li>
              <li class="flex gap-2">
                <span class="text-purple-600">3.</span>
                <span><strong>Multi-Algorithm Scoring:</strong> Runs parallel assessments</span>
              </li>
              <li class="flex gap-2">
                <span class="text-purple-600">4.</span>
                <span><strong>Benchmarking:</strong> Compares vs top performers</span>
              </li>
              <li class="flex gap-2">
                <span class="text-purple-600">5.</span>
                <span><strong>Synthesis:</strong> Generates actionable insights</span>
              </li>
              <li class="flex gap-2">
                <span class="text-purple-600">6.</span>
                <span><strong>Auto-Generation:</strong> Creates optimized variations</span>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Navigation -->
      <div class="flex justify-between mt-6">
        <button
          @click="prevStage"
          :disabled="currentStage === 0"
          class="flex items-center gap-2 px-6 py-3 bg-gray-700 text-white rounded-lg font-medium hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg"
        >
          <ArrowLeft :size="20" />
          Previous
        </button>

        <button
          v-if="currentStage < stages.length - 1"
          @click="nextStage"
          class="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-lg font-medium hover:from-indigo-700 hover:to-purple-700 transition-all shadow-lg"
        >
          Next Question
          <ArrowRight :size="20" />
        </button>

        <button
          v-else
          @click="downloadReport"
          class="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-green-600 to-emerald-600 text-white rounded-lg font-medium hover:from-green-700 hover:to-emerald-700 transition-all shadow-lg"
        >
          <CheckCircle :size="20" />
          Complete & Download
        </button>
      </div>
    </div>
  </div>
</template>

